DataTorrent/moodI

operators/library/pom.xml
operators/library/src/main/java/com/datatorrent/lib/schemaAware/CsvFormatter.java
operators/library/src/main/java/com/datatorrent/lib/schemaAware/CsvParser.java
operators/library/src/main/java/com/datatorrent/lib/schemaAware/FilterOperator.java
operators/library/src/main/java/com/datatorrent/lib/schemaAware/JdbcOutputOperator.java
operators/library/src/main/java/com/datatorrent/lib/schemaAware/JdbcPOJOPollInputOperator.java
operators/library/src/main/java/com/datatorrent/lib/schemaAware/JsonFormatter.java
operators/library/src/main/java/com/datatorrent/lib/schemaAware/JsonParser.java
operators/library/src/main/java/com/datatorrent/lib/schemaAware/POJOEnricher.java
operators/library/src/main/java/com/datatorrent/lib/schemaAware/SchemaAwareOperatorUtils.java
operators/library/src/main/java/com/datatorrent/lib/schemaAware/TimeBasedDedupOperator.java
operators/library/src/main/java/com/datatorrent/lib/schemaAware/TransformOperator.java
operators/library/src/test/java/com/datatorrent/lib/schemaAware/CsvFormatterTest.java
operators/library/src/test/java/com/datatorrent/lib/schemaAware/CsvParserTest.java
operators/library/src/test/java/com/datatorrent/lib/schemaAware/FilterOperatorTest.java
operators/library/src/test/java/com/datatorrent/lib/schemaAware/JdbcPOJOPollInputOperatorTest.java
operators/library/src/test/java/com/datatorrent/lib/schemaAware/JsonFormatterTest.java
operators/library/src/test/java/com/datatorrent/lib/schemaAware/JsonParserTest.java
operators/library/src/test/java/com/datatorrent/lib/schemaAware/POJOEnricherTest.java
operators/library/src/test/java/com/datatorrent/lib/schemaAware/TimeBasedDedupOperatorTest.java
operators/library/src/test/java/com/datatorrent/lib/schemaAware/TransformOperatorTest.java
operators/library/src/test/resources/csvSchema.json

@chinmaykolhatkar Could you review the operator code
This can be merged once  https://github.com/DataTorrent/moodI/pull/1 is merged

SPOI-11360 

---

operators/library/src/main/java/com/datatorrent/lib/schemaAware/JsonParser.java
operators/library/src/main/java/com/datatorrent/lib/schemaAware/POJOEnricher.java
operators/library/src/main/java/com/datatorrent/lib/schemaAware/SchemaAwareOperatorUtils.java
operators/library/src/main/java/com/datatorrent/lib/schemaAware/TransformOperator.java
operators/library/src/test/java/com/datatorrent/lib/schemaAware/TimeBasedDedupOperatorTest.java
pom.xml

@chaithu14 Please review and merge

updated malhar version to 3.7

---

operators/library/src/main/java/com/datatorrent/fs/s3/S3RecordReaderWrapperModule.java

SPOI-11879 Custom S3RecordReader module to simplify s3files

---

app-templates/README.md
app-templates/database-to-database-sync/README.md
app-templates/database-to-hdfs/README.md
app-templates/hdfs-hdfs-transform/README.md
app-templates/hdfs-line-copy/README.md
app-templates/hdfs-part-file-copy/README.md
app-templates/hdfs-sync/README.md
app-templates/hdfs-to-kafka-sync/README.md
app-templates/hdfs-to-s3-sync/README.md
app-templates/kafka-to-cassandra-transform/README.md
app-templates/kafka-to-database-sync/README.md
app-templates/kafka-to-hdfs-filter-transform/README.md
app-templates/kafka-to-hdfs-filter/README.md
app-templates/kafka-to-hdfs-sync/README.md
app-templates/kafka-to-kafka-transform/README.md
app-templates/kinesis-to-redshift/README.md
app-templates/kinesis-to-s3/README.md
app-templates/s3-to-hdfs-sync/README.md
app-templates/s3-to-redshift/README.md

1) Fixed the github url in app templates. 2) Copied the README file from app-templates repo

---

app-templates/hdfs-part-file-copy/README.md

SPOI-11434 Update Logical DAG and properties link in hdfs-part-file-copy app template.

---

operators/library/pom.xml
operators/library/src/main/java/com/datatorrent/lib/schemaAware/CassandraOutputOperator.java

@deepak-narkhede please review and merge

SPOI-11967 Schema Aware Cassandra Output Operator

---

app-templates/kafka-to-cassandra-filter-transform/pom.xml
app-templates/kinesis-to-s3/pom.xml
app-templates/kinesis-to-s3/src/assemble/appPackage.xml
app-templates/kinesis-to-s3/src/main/java/com/datatorrent/apps/Application.java
app-templates/kinesis-to-s3/src/main/resources/META-INF/properties.xml
app-templates/kinesis-to-s3/src/main/resources/resources/ui/dashboards/kinesis-to-S3.dtdashboard
app-templates/kinesis-to-s3/src/main/resources/resources/ui/ui.json
app-templates/pom.xml
operators/contrib/aws-connectors/src/main/java/com/datatorrent/metrics/KinesisByteArrayInputOperator.java
operators/contrib/pom.xml
operators/library/src/main/java/com/datatorrent/lib/metrics/S3Reconciler.java

1) Created dashboard for Kinesis to S3 App template. 2) Fixed the pom dependency issues

---

app-templates/pom.xml
app-templates/s3-to-redshift/pom.xml
app-templates/s3-to-redshift/src/main/java/com/datatorrent/apps/Application.java
app-templates/s3-to-redshift/src/main/resources/META-INF/properties.xml
operators/library/pom.xml
operators/library/src/main/java/com/datatorrent/fs/s3/S3RecordReaderWrapperModule.java
operators/library/src/main/java/com/datatorrent/lib/converter/StringToByteArrayConverterOperator.java
operators/library/src/main/java/com/datatorrent/lib/metrics/FSRecordReader.java
operators/library/src/main/java/com/datatorrent/lib/metrics/RedshiftJdbcTransactionableOutputOperator.java
operators/library/src/main/java/com/datatorrent/lib/metrics/RedshiftOutputModule.java
operators/library/src/main/java/com/datatorrent/lib/metrics/S3RecordReader.java

@yogidevendra Please review  and merge.

SPOI-11568 Added metrics for S3 input and Redshift Output

---

app-templates/kinesis-to-s3/src/main/java/com/datatorrent/apps/Application.java
app-templates/pom.xml
app-templates/s3-to-redshift/pom.xml
app-templates/s3-to-redshift/src/main/java/com/datatorrent/apps/Application.java
app-templates/s3-to-redshift/src/main/resources/resources/ui/dashboards/S3-to-redshift.dtdashboard
app-templates/s3-to-redshift/src/main/resources/resources/ui/ui.json
operators/contrib/aws-connectors/pom.xml
operators/contrib/aws-connectors/src/main/java/com/datatorrent/moodi/kinesis/KinesisByteArrayInputOperator.java
operators/contrib/aws-connectors/src/main/java/com/datatorrent/moodi/lib/db/RedshiftJdbcTransactionableOutputOperator.java
operators/contrib/aws-connectors/src/main/java/com/datatorrent/moodi/lib/db/RedshiftOutputModule.java
operators/contrib/aws-connectors/src/main/java/com/datatorrent/moodi/lib/io/fs/s3/S3MetricsTupleOutputModule.java
operators/contrib/aws-connectors/src/main/java/com/datatorrent/moodi/lib/io/fs/s3/S3Reconciler.java
operators/contrib/aws-connectors/src/main/java/com/datatorrent/moodi/lib/io/fs/s3/S3RecordReader.java
operators/contrib/aws-connectors/src/main/java/com/datatorrent/moodi/lib/io/fs/s3/S3RecordReaderWrapperModule.java
operators/library/pom.xml
operators/library/src/main/java/com/datatorrent/moodi/lib/io/fs/FSRecordCompactionOperator.java
operators/library/src/main/java/com/datatorrent/moodi/lib/io/fs/FSRecordReader.java

SPOI-11568 1) Incorporated review comments 2) Added dashboard for S3 to Redshift App template

---

app-templates/hdfs-line-copy/pom.xml
app-templates/hdfs-line-copy/src/main/java/com/datatorrent/apps/Application.java
app-templates/hdfs-line-copy/src/main/resources/META-INF/properties.xml
app-templates/hdfs-line-copy/src/main/resources/resources/ui/dashboards/HDFS-line-copy.dtdashboard
app-templates/hdfs-line-copy/src/main/resources/resources/ui/ui.json
app-templates/pom.xml
operators/library/src/main/java/com/datatorrent/moodi/io/fs/StringFileOutputOperator.java
operators/library/src/main/java/com/datatorrent/moodi/lib/io/fs/FSRecordReaderModule.java

SPOI-11560 1) Added metrics for StringFileOutputOperator. 2)Added dashboard

---

operators/library/src/main/java/com/datatorrent/moodi/lib/io/fs/batch/AbstractBatchFileInputOperator.java
operators/library/src/main/java/com/datatorrent/moodi/lib/io/fs/batch/AbstractBatchFileOutputOperator.java
operators/library/src/main/java/com/datatorrent/moodi/lib/io/fs/batch/BatchBasedLineByLineFileInputOperator.java
operators/library/src/test/java/com/datatorrent/moodi/lib/io/fs/batch/AbstractBatchFileInputOperatorTest.java

@bhupeshchawda Kindly review and merge

SPOI-11620 Change of package for batch file IO operators

---

operators/library/src/main/java/com/datatorrent/moodi/lib/io/db/batch/BatchJdbcPOJOInputOperator.java
operators/library/src/main/java/com/datatorrent/moodi/lib/io/db/batch/JdbcPOJOInputOperator.java

@bhupeshchawda Kindly review and merge!

SPOI-11619 Change of package for batch jdbc input operator

---

app-templates/kinesis-to-redshift/LICENSE
app-templates/s3-to-redshift/LICENSE

@ashwinchandrap Please review and merge.

SPOI-12088 Added the redshift jdbc driver licenses in app templates

---

app-templates/hdfs-line-copy/src/main/resources/META-INF/properties.xml

Add the line delimiter as empty in csv formater

---

app-templates/pom.xml
app-templates/s3-to-hdfs-sync/pom.xml
app-templates/s3-to-hdfs-sync/src/main/java/com/datatorrent/apps/Application.java
app-templates/s3-to-hdfs-sync/src/main/resources/META-INF/properties.xml
app-templates/s3-to-hdfs-sync/src/main/resources/ui/dashboards/S3-to-HDFS-Sync.dtdashboard
app-templates/s3-to-hdfs-sync/src/main/resources/ui/ui.json
operators/contrib/aws-connectors/src/main/java/com/datatorrent/moodi/lib/io/fs/s3/S3BlockReader.java
operators/contrib/aws-connectors/src/main/java/com/datatorrent/moodi/lib/io/fs/s3/S3InputModule.java
operators/library/src/main/java/com/datatorrent/moodi/io/fs/BlockWriter.java
operators/library/src/main/java/com/datatorrent/moodi/io/fs/FSInputModule.java
operators/library/src/main/java/com/datatorrent/moodi/io/fs/FSSliceReader.java
operators/library/src/main/java/com/datatorrent/moodi/io/fs/FileSplitterInput.java
operators/library/src/main/java/com/datatorrent/moodi/io/fs/HDFSFileCopyModule.java
operators/library/src/main/java/com/datatorrent/moodi/io/fs/HDFSFileMerger.java

Add metrics to operators in S3 to HDFS Sync app along with dashboards

SPOI-11567 Add metrics to operators in S3 to HDFS Sync app.

---

app-templates/kafka-to-cassandra-filter-transform/pom.xml
app-templates/kafka-to-database-sync/pom.xml
app-templates/kafka-to-kafka-filter-transform/pom.xml
operators/library/src/main/java/com/datatorrent/moodi/lib/io/fs/FSRecordReader.java

1) Fixed the block reader repartition issue. 2) Removed the exclude dependency from malhar-kafka dependency

---

app-templates/hdfs-line-copy/src/main/java/com/datatorrent/apps/Application.java
app-templates/s3-to-redshift/src/main/java/com/datatorrent/apps/Application.java
app-templates/s3-to-redshift/src/main/resources/META-INF/properties.xml
operators/contrib/aws-connectors/src/main/java/com/datatorrent/moodi/lib/io/fs/s3/S3RecordReader.java

SPOI-12157 1) Fixed the S3RecordReader partition issue 2) Exposed the maxReaders, minReaders, blocksize parameters.

---

app-templates/s3-to-redshift/src/main/java/com/datatorrent/apps/Application.java
app-templates/s3-to-redshift/src/main/resources/META-INF/properties.xml
operators/contrib/aws-connectors/src/main/java/com/datatorrent/moodi/lib/db/RedshiftOutputModule.java
operators/contrib/aws-connectors/src/main/java/com/datatorrent/moodi/lib/io/fs/s3/S3MetricsTupleOutputModule.java

1) Disabled the dynamic partition of S3TupleOutputModule. 2) Added the partition parallel to S3TupleOutputModule.

---

app-templates/hdfs-line-copy/src/main/resources/META-INF/properties.xml
app-templates/hdfs-to-hdfs-filter-transform/src/main/resources/META-INF/properties.xml
app-templates/kinesis-to-redshift/src/main/resources/META-INF/properties.xml
app-templates/kinesis-to-s3/src/main/java/com/datatorrent/apps/Application.java
app-templates/kinesis-to-s3/src/main/resources/META-INF/properties.xml
app-templates/s3-to-redshift/src/main/resources/META-INF/properties.xml

SPOI-12283 Disable the reader dynamic partition in app templates

---

app-templates/database-to-database-sync/README.md
app-templates/hdfs-line-copy/README.md
app-templates/hdfs-part-file-copy/README.md
app-templates/kafka-to-hdfs-filter-transform/README.md

1. database-to-database-sync
2. hdfs-line-copy
3. hdfs-part-file-copy
4. kafka-to-hdfs-filter-transform

SPOI-12043 README files

---

app-templates/hdfs-to-hdfs-filter-transform/README.md
app-templates/kafka-to-cassandra-filter-transform/README.md
app-templates/kafka-to-hdfs-filter-transform/README.md

1. hdfs-to-hdfs-filter-transform
2. kafka-to-cassandra-filter-transform

SPOI-12043-readme-phase2

---

app-templates/s3-to-redshift/pom.xml
app-templates/s3-to-redshift/src/main/resources/resources/ui/dashboards/S3-to-redshift.dtdashboard
operators/contrib/aws-connectors/pom.xml

@yogi: Please review and merge.

1) Recreated the dashboard. 2) Excluded the jackson dependency.

---

app-templates/kinesis-to-redshift/pom.xml
app-templates/kinesis-to-redshift/src/main/resources/resources/ui/dashboards/Kinesis-to-Redshift.dtdashboard

@yogi Please review and merge.

1) Recreated the dashboard for Kinesis to Redshift. 2) Excluded the jackson dependency.

---

app-templates/database-to-hdfs/README.md
app-templates/hdfs-sync/README.md
app-templates/hdfs-to-kafka-sync/README.md
app-templates/hdfs-to-s3-sync/README.md
app-templates/kafka-to-elastic-search-transform/README.md
app-templates/kafka-to-hdfs-filter/README.md
app-templates/kafka-to-hdfs-sync/README.md

SPOI-12383 Fixed the video links in README files

---

app-templates/hdfs-to-hdfs-filter-transform/README.md
app-templates/hdfs-to-s3-sync/README.md
app-templates/kafka-to-cassandra-filter-transform/README.md
app-templates/kafka-to-database-sync/README.md
app-templates/kafka-to-hdfs-sync/README.md
app-templates/kafka-to-kafka-filter-transform/README.md
app-templates/kinesis-to-s3/README.md
app-templates/s3-to-redshift/README.md

SPOI-11875 Fixed the links and descriptions in README files

---

app-templates/hdfs-sync/src/assemble/appPackage.xml

BUGFIX: Add missing fileSet closing tag in appPackage.xml

---

utils/azure/hdinsight-with-Datatorrent-RTS/README.md
utils/azure/hdinsight-with-Datatorrent-RTS/azuredeploy.json
utils/azure/hdinsight-with-Datatorrent-RTS/azuredeploy.parameters.json
utils/azure/hdinsight-with-Datatorrent-RTS/metadata.json
utils/azure/hdinsight-with-Datatorrent-RTS/scripts/InstallDTRTS.sh

1. Azure deployment template, script for RTS installation.

SPOI-10488-azure-deployment-template

---

utils/azure/hdinsight-with-Datatorrent-RTS/scripts/InstallDTRTS.sh

1. creating user before calling installer

SPOI-12825-apps-import-issue

---

app-templates/hdfs-to-s3-sync/pom.xml

SPOI-13034 Fix the jackson library issue

---

app-templates/hdfs-line-copy/pom.xml
app-templates/s3-to-hdfs-sync/pom.xml
operators/library/pom.xml

@tushargosavi Please review and merge.

SPOI-13040 Removed the SNAPSHOT dependencies from app-templates and operators module

---

utils/azure/hdinsight-with-Datatorrent-RTS/scripts/InstallDTRTS.sh

SPOI-12825-gateway-restart-sleep

---

operators/library/src/main/java/com/datatorrent/lib/schemaAware/JsonParser.java
operators/library/src/main/java/com/datatorrent/lib/schemaAware/TransformOperator.java
operators/library/src/test/java/com/datatorrent/lib/schemaAware/TransformOperatorTest.java

@chinmaykolhatkar @PramodSSImmaneni @sanjaypujare please see

SPOI-13095 Schema Aware operators should not perform validations in setter methods

---

utils/azure/hdinsight-with-Datatorrent-RTS/azuredeploy.json

1. Changed tooltip for edge node VM size.

SPOI-13233-azure-tooltip-fix

---

app-templates/s3-to-hdfs-sync/pom.xml

SPOI-13586 Fixed pom

---

app-templates/hdfs-to-s3-sync/pom.xml
app-templates/kafka-to-hdfs-filter-transform/pom.xml
app-templates/kafka-to-hdfs-filter/pom.xml
app-templates/kafka-to-kafka-filter-transform/pom.xml
app-templates/kinesis-to-redshift/pom.xml
app-templates/kinesis-to-s3/pom.xml
app-templates/s3-to-hdfs-sync/pom.xml
app-templates/s3-to-redshift/pom.xml

@sumansanjeev Please review and merge

Updated version of apps which changed since last release to 0.12.0
